namespace MusicPipeline.Profiles;

//you can mark this class static because all of its members are static
// Gotcha
public static class DefaultProfiles
{
	// OK I have decided that the default profile shall be fully sandboxed

	public static readonly Profile DefaultProfile = new Profile
	{
		Name = "Default",
		BackupDir = @"C:\MusicTools\MusicPipeline\Sandbox\Sandbox_Backup",
		CompressedDirs = [@"C:\MusicTools\MusicPipeline\Sandbox\Sandbox_Mobile"],
		BrokenSongsFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\broken_songs.json",
		DiagLogFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\csLogFile.log",
		CacheFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\dashboard_cache.json",
		TimingFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\timing_history.json",
		CookieFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\cookies.txt",
		HistoryFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\downloaded_history.txt",
		ProfileFile = @"C:\MusicTools\MusicPipeline\Sandbox\Config\csProfiles.json",
		YTDLPExe = @"C:\MusicTools\yt-dlp.exe",
		FFmpegExe = @"C:\MusicTools\ffmpeg.exe",
		FirefoxExe = @"C:\Program Files\Mozilla Firefox\firefox.exe",
		CheckURL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		RootDir = @"C:\MusicTools\MusicPipeline\Sandbox",
		ScriptRootDir = @"C:\MusicTools\MusicPipeline",
		OutputTemplate = "{backupDir}/%(artist|uploader).250s/%(album|playlist).250s/%(title).250s.%(ext)s",
		YTDLPConfigFileOriginal = @"C:\MusicTools\MusicPipeline\Sandbox\Config\yt-dlp.conf.original",
		YTDLPConfigFile = "Null",
		SleepInterval = 4,
		MaxSleepInterval = 12, 
		SleepRequests = 3,
		MaxCompressThreads = 8,
		MaxDownloadThreads = 6,
		MaxLyricThreads = 3,
		ScannerSleepIntervalSec = 60,
		ChronDaemonSleepSec = 1800,
		MaxStreamReturnLines = 15000,
		StartingWebServerPort = 50001,
		NormalIntervalSec = 1800,
		CleanIntervalSec = 604800,
		NormalStep1 = true,
		NormalStep2 = true,
		NormalStep3 = true,
		NormalStep4 = true,
		NormalStep5 = true,
		NormalStep6 = true,
		NormalStep7 = true,
		CleanSweepDownload = true,
		CleanSweepLyrics = true,
		CleanSweepCompress = true,
		CleanSweepLore = true,
		Playlists = [
		"https://music.youtube.com/playlist?list=PLqcuYaDDgyad1-o1HTVnTiZKoluY5enwk"
		],
		LastCleanRunEpoch = 1785532108,
		LastNormalRunEpoch = 1785673837,
		LogEngine = new(@"C:\MusicTools\MusicPipeline\Sandbox\Config\csLogFile.log")
	};

	//This is the actual one, not to be used until pushing to production
	public static readonly Profile WorkingDefaultProfile = new Profile
	{
		Name = "Working Default",
		BackupDir = @"C:\Users\filip\Music\YT_Music_Backup",
		CompressedDirs = [@"C:\Users\filip\Music\YT_Music_Mobile"],
		BrokenSongsFile = @"C:\MusicTools\MusicPipeline\Config\broken_songs.json",
		DiagLogFile = @"C:\MusicTools\MusicPipeline\Config\web_console_stream.log",
		CacheFile = @"C:\MusicTools\MusicPipeline\Config\dashboard_cache.json",
		TimingFile = @"C:\MusicTools\MusicPipeline\Config\timing_history.json",
		CookieFile = @"C:\MusicTools\MusicPipeline\Config\cookies.txt",
		HistoryFile = @"C:\MusicTools\MusicPipeline\Config\downloaded_history.txt",
		ProfileFile = @"TODO",
		YTDLPExe = @"C:\MusicTools\yt-dlp.exe",
		FFmpegExe = @"C:\MusicTools\ffmpeg.exe",
		FirefoxExe = @"C:\Program Files\Mozilla Firefox\firefox.exe",
		CheckURL = @"https://www.youtube.com/watch?v=dQw4w9WgXcQ",
		RootDir = @"C:\MusicTools\MusicPipeline",
		ScriptRootDir = @"C:\MusicTools",
		OutputTemplate = "{backupDir}/%(artist|uploader).250s/%(album|playlist).250s/%(title).250s.%(ext)s",
		YTDLPConfigFileOriginal = @"C:\MusicTools\MusicPipeline\Config\yt-dlp.conf",
		YTDLPConfigFile = "Null",
		SleepInterval = 4,
		MaxSleepInterval = 12, 
		SleepRequests = 3,
		MaxCompressThreads = 8,
		MaxDownloadThreads = 6,
		MaxLyricThreads = 3,
		ScannerSleepIntervalSec = 60,
		ChronDaemonSleepSec = 1800,
		MaxStreamReturnLines = 15000,
		StartingWebServerPort = 50001,
		NormalIntervalSec = 1800,
		CleanIntervalSec = 604800,
		NormalStep1 = true,
		NormalStep2 = true,
		NormalStep3 = true,
		NormalStep4 = true,
		NormalStep5 = true,
		NormalStep6 = true,
		NormalStep7 = true,
		CleanSweepDownload = true,
		CleanSweepLyrics = true,
		CleanSweepCompress = true,
		CleanSweepLore = true,
		Playlists = [
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyacWpBG6ib-2EKOuQa6aGjZJ",
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyaeHKssVjz_Nw3qUDwfrwL09",
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyad_i19iLheoQJLLKJUtwlAr",
		"https://www.youtube.com/playlist?list=PLqcuYaDDgyach02bt_8R8G7AzE9zSAOkS"
		],
		LastCleanRunEpoch = 1785532108,
		LastNormalRunEpoch = 1785673837,
		LogEngine = new(@"C:\MusicTools\MusicPipeline\Config\web_console_stream.log")
	};

	// Swap default with null

	public static readonly Profile ErrorProfile = new Profile
	{
		Name = "ERROR",
		BackupDir = "ERROR",
		CompressedDirs = ["ERROR"],
		BrokenSongsFile = "ERROR",
		DiagLogFile = "ERROR",
		CacheFile = "ERROR",
		TimingFile = "ERROR",
		CookieFile = "ERROR",
		HistoryFile = "ERROR",
		ProfileFile = "ERROR",
		YTDLPExe = "ERROR",
		FFmpegExe = "ERROR",
		FirefoxExe = "ERROR",
		CheckURL = "ERROR",
		RootDir = "ERROR",
		ScriptRootDir = "ERROR",
		OutputTemplate = "ERROR",
		YTDLPConfigFileOriginal = "ERROR",
		YTDLPConfigFile = "ERROR",
		SleepInterval = 2147483647,
		MaxSleepInterval = 2147483647, 
		SleepRequests = 2147483647,
		MaxCompressThreads = 2147483647,
		MaxDownloadThreads = 2147483647,
		MaxLyricThreads = 2147483647,
		ScannerSleepIntervalSec = 2147483647,
		ChronDaemonSleepSec = 2147483647,
		MaxStreamReturnLines = 2147483647,
		StartingWebServerPort = 2147483647,
		NormalIntervalSec = 2147483647,
		CleanIntervalSec = 2147483647,
		NormalStep1 = true,
		NormalStep2 = true,
		NormalStep3 = true,
		NormalStep4 = true,
		NormalStep5 = true,
		NormalStep6 = true,
		NormalStep7 = true,
		CleanSweepDownload = true,
		CleanSweepLyrics = true,
		CleanSweepCompress = true,
		CleanSweepLore = true,
		Playlists = [
		"ERROR",
		"ERROR",
		"ERROR",
		"ERROR"
		],
		LastCleanRunEpoch = 2147483647,
		LastNormalRunEpoch = 2147483647,
		LogEngine = new("ERROR", "ERROR")
	};
}