--no-colors 
# Removes colouring from the output, as it would likely mess with the logEngine colouring
#^ TODO: test without

--verbose 
# Provides full output, necessary for working out which songs broke

--newline 
# Outputs progress bar as new lines, otherwise it would just edit the previous line which doesn't play nice with logging

--sleep-interval {SleepInterval} 
# Minimum bound for how long to sleep between videos

--max-sleep-interval {MaxSleepInterval} 
# Sleep length randomly chosen between --sleep-interval and this, to emulate a human and hopefully not get flagged

--sleep-requests {SleepRequests} 
# How long to sleep between every api request, so as to not get throttled or rate limited

--embed-thumbnail 
# Embed thumbnail into the video file as cover art

--convert-thumbnails jpg 
# Convert thumbnail to jpg, or any format for consistency
#^ I don't know why jpg is used, 
#^^ TODO: Test different thumbnail formats for size

--ppa EmbedThumbnail+ffmpeg_o:-vf crop=ih:ih
# PostProccessor arguments. This gives the following arguments to ffmpeg when using EmbedThumbnail
#^ -vf Video Feed, the thumbnail is embedded as the songs cover art
#^^ crop=ih:ih crop to a square by the image height
#^^^ NOTE: This doesn't seem to work, unless it was added after the existing files on my phone were generated, so a postprocessing step may have to be done in c# to fix that

--embed-metadata 
# Embeds youtube metadata into the output file

--parse-metadata title:%(artist)s - %(title)s 
# Parse metadata so that the title equals Artist - Title
#^ This may not be what I want. Further testing required

--parse-metadata uploader:%(artist)s 
# Sets the artist to the uploader

--no-keep-video 
# Only download the audio stream

--force-overwrites 
# If a file exists, overwrite it
#^ This is used because a history file is also provided, and if that history file does not contain the video,
#^^ Then we must have removed that for a reason like the video being downloaded incorrectly, so you want to overwrite with the correct video

--cookies "{CookieFile}"
# The cookie file

-P "{BackupDir}"
# Download intermediary files to the backup directory

-o "{BackupDir}/%(artist|uploader).250s/%(album|playlist).250s/%(title).250s.%(ext)s"
# Use the provided output template to define the path of the output file
#^ This a variable that can be changed in the profile
#^^ TODO: Make some way for the profile to define these whole arguments

--write-subs
# Write subtitle files (For lyrics embedded in subtitles or like luke pickman's videos where he puts the current instrument name in the subtitles)

--write-auto-subs 
# In case the auto subtitles are good
#^ Could be better than nothing once the lyric step comes through

--sub-format ass/srt/vtt/best
# Pretty good formats

--sub-langs all
# All 

--cache-dir "{RootDir}\Config\.cache"
# Cache things like downloaders and page stuff

--geo-bypass 
# It tries to bypass georestrictions

--js-runtime deno 
# Use the deno Javascript runtime to handle challenges

--extractor-args youtube:player_js_variant=tv 
# Pretend to be a youtube tv client to get easier javascript challenges; TVs are dumb and not very powerful

-f bestaudio/best 
# Choose the best audio stream quality to download

--extract-audio 
# Extract the audio streams (duh)

--audio-format m4a 
# Use m4a as the audio format to output

--audio-quality 0 
# 0 is best

--download-archive "{HistoryFile}"
# The history file containing all the processed songs

#--ignore-errors 
# If a song fails, continue

--no-abort-on-error 
# See above

--legacy-server-connect 
# Supports connecting to legacy youtube servers
#^ Per YTDLPs README "Explicitly allow HTTPS connection to servers that do not support RFC 5746 secure renegotiation"

--socket-timeout 30 
# If the socket is quiet for more than 30 seconds, give up