Param (
    [string]$ConfigDir = "C:\MusicTools\MusicPipeline\Config",
    [string]$HistoryPath = "C:\MusicTools\MusicPipeline\Config\downloaded_history.txt",
    [string]$FirefoxPath = "C:\Program Files\Mozilla Firefox\firefox.exe"
)

$ErrorDbPath  = Join-Path $ConfigDir "broken_songs.json"
$BrokenTracks = [System.Collections.Generic.List[PSCustomObject]]::new()

# Locate all temp playlist run error logs generated by Download.ps1
$ErrorLogs = Get-ChildItem -Path $ConfigDir -Filter "playlist*_run_errors.txt" -File

foreach ($Log in $ErrorLogs) {
    if ($Log.Length -eq 0) { continue }
    
    $RawLines = Get-Content -LiteralPath $Log.FullName -ErrorAction SilentlyContinue
    $CurrentPlaylistIndex = if ($Log.BaseName -match '\d+') { $Matches[0] } else { "Unknown" }

    # Parse errors block-by-block
    for ($i = 0; $i -lt $RawLines.Count; $i++) {
        $Line = $RawLines[$i]

        # Extract failed video IDs and failure signatures
        if ($Line -match "ERROR:\s*\[youtube\]\s*([^:]+):\s*(.*)") {
            $VideoID = $逃Matches[1] = $Matches[1].Trim()
            $Reason  = $Matches[2].Trim()
            
            # Lookahead logic to catch trailing context warnings
            if ($i + 1 -lt $RawLines.Count -and $RawLines[$i+1] -match "Sign in to confirm|Video unavailable|private") {
                $Reason += " ($($RawLines[$i+1].Trim()))"
            }

            # Avoid duplication across thread sweeps
            if (-not ($BrokenTracks.VideoID -contains $VideoID)) {
                $BrokenTracks.Add([PSCustomObject]@{
                    id         = [string][Guid]::NewGuid().Guid.Substring(0,8) # Unique element handle for UI
                    videoId    = $VideoID
                    title      = "Track ID: $VideoID" # yt-dlp fallback title when extraction fails
                    playlist   = "Playlist $CurrentPlaylistIndex"
                    reason     = $Reason
                    detectedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
                })
            }
        }
    }
end

# Preserve existing un-resolved manual records if fix.ps1 reruns
if (Test-Path $ErrorDbPath) {
    $ExistingDb = Get-Content -LiteralPath $ErrorDbPath -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json
    foreach ($Item in $ExistingDb) {
        if (-not ($BrokenTracks.videoId -contains $Item.videoId)) {
            $BrokenTracks.Add($Item)
        }
    }
}

# Commit to the server database
$BrokenTracks | ConvertTo-Json -Depth 4 | Out-File -FilePath $ErrorDbPath -Encoding utf8 -Force
Write-Output "[FIX ENGINE] Analysis finished. Active anomalies compiled to broken_songs.json."