Param (
    [string]$ConfigDir = "C:\MusicTools\MusicPipeline\Config",
    [string]$HistoryPath = "C:\MusicTools\MusicPipeline\Config\downloaded_history.txt",
    [string]$FirefoxPath = "C:\Program Files\Mozilla Firefox\firefox.exe",
    [string]$YTDLPPath = "C:\MusicTools\yt-dlp.exe",
    [string]$CookiePath = "C:\MusicTools\MusicPipeline\Config\cookies.txt",
    [string]$BackupDir = "C:\Users\filip\Music\YT_Music_Backup",
    [string]$ProtonCLI = "C:\Program Files\Proton\VPN\ProtonVPN.Backend.CLI.exe",
    [bool]$AutoRecover = $false
)

$ErrorDbPath  = Join-Path $ConfigDir "broken_songs.json"
$BrokenTracks = [System.Collections.Generic.List[PSCustomObject]]::new()

# Locate all temp playlist run error logs generated by Download.ps1
$ErrorLogs = Get-ChildItem -Path $ConfigDir -Filter "playlist*_run_errors.txt" -File

foreach ($Log in $ErrorLogs) {
    if ($Log.Length -eq 0) { continue }
    
    $RawLines = Get-Content -LiteralPath $Log.FullName -ErrorAction SilentlyContinue
    $CurrentPlaylistIndex = if ($Log.BaseName -match '\d+') { $Matches[0] } else { "Unknown" }

    # Parse errors block-by-block
    for ($i = 0; $i -lt $RawLines.Count; $i++) {
        $Line = $RawLines[$i]

        # Extract failed video IDs and failure signatures
        if ($Line -match "ERROR:\s*\[youtube\]\s*([^:]+):\s*(.*)") {
            $VideoID = $Matches[1].Trim()
            $Reason  = $Matches[2].Trim()
            
            # Lookahead logic to catch trailing context warnings
            if ($i + 1 -lt $RawLines.Count -and $RawLines[$i+1] -match "Sign in to confirm|Video unavailable|private|not made this video available") {
                $Reason += " ($($RawLines[$i+1].Trim()))"
            }

            # Avoid duplication across thread sweeps
            if (-not ($BrokenTracks.VideoID -contains $VideoID)) {
                $BrokenTracks.Add([PSCustomObject]@{
                    id         = [string][Guid]::NewGuid().Guid.Substring(0,8) # Unique element handle for UI
                    videoId    = $VideoID
                    title      = "Track ID: $VideoID" # yt-dlp fallback title when extraction fails
                    playlist   = "Playlist $CurrentPlaylistIndex"
                    reason     = $Reason
                    detectedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
                })
            }
        }
    }
}

# Preserve existing un-resolved manual records if fix.ps1 reruns
if (Test-Path $ErrorDbPath) {
    $ExistingDb = Get-Content -LiteralPath $ErrorDbPath -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json
    foreach ($Item in $ExistingDb) {
        if (-not ($BrokenTracks.videoId -contains $Item.videoId)) {
            $BrokenTracks.Add($Item)
        }
    }
}

# Commit to the server database
$BrokenTracks | ConvertTo-Json -Depth 4 | Out-File -FilePath $ErrorDbPath -Encoding utf8 -Force
Write-Output "[FIX ENGINE] Analysis finished. Active anomalies compiled to broken_songs.json."

# Local Standalone Console Trigger Automation (Fallback)
if ($AutoRecover) {
    $GeoTracks = $BrokenTracks | Where-Object { $_.reason -match "available in your country|GeoRestrictedError|not made this video available" }
    if ($GeoTracks.Count -gt 0 -and (Test-Path $ProtonCLI)) {
        Write-Output "[*] Running standalone CLI recovery for $($GeoTracks.Count) country-restricted tracks..."
        & $ProtonCLI c --cc US
        Start-Sleep -Seconds 8
        $Recovered = @()
        foreach ($Track in $GeoTracks) {
            $Url = "https://www.youtube.com/watch?v=$($Track.videoId)"
            & $YTDLPPath --no-colors --embed-metadata --embed-thumbnail --convert-thumbnails jpg -f "ba[ext=m4a]/ba" --cookies $CookiePath -P $BackupDir $Url
            if ($LASTEXITCODE -eq 0) { $Recovered += $Track.videoId }
        }
        & $ProtonCLI d
        if ($Recovered.Count -gt 0) {
            $CurrentDb = Get-Content -LiteralPath $ErrorDbPath -Raw | ConvertFrom-Json
            $CleanedDb = $CurrentDb | Where-Object { $Recovered -notcontains $_.videoId }
            $CleanedDb | ConvertTo-Json -Depth 4 | Out-File -FilePath $ErrorDbPath -Encoding utf8 -Force
        }
    }
}