Param (
    [string]$ConfigDir = "C:\MusicTools\MusicPipeline\Config",
    [string]$HistoryPath = "C:\MusicTools\MusicPipeline\Config\downloaded_history.txt",
    [string]$FirefoxPath = "C:\Program Files\Mozilla Firefox\firefox.exe",
    [string]$YTDLPPath = "C:\MusicTools\yt-dlp.exe",
    [string]$CookiePath = "C:\MusicTools\MusicPipeline\Config\cookies.txt",
    [string]$BackupDir = "C:\Users\filip\Music\YT_Music_Backup",
    [string]$ProtonCLI = "C:\Program Files\Proton\VPN\ProtonVPN.Backend.CLI.exe",
    [string]$GlobalLogFile = "C:\MusicTools\MusicPipeline\Config\web_console_stream.log"
    [bool]$AutoRecover = $false
)

# -----------------------------------------------------------------
# CORE DETERMINISTIC SHA-256 UUID GENERATOR
# -----------------------------------------------------------------
function Get-TrackUUID([string]$Artist, [string]$Album, [string]$Title) {
    $RawIdentity = "$Artist-$Album-$Title".ToLower().Trim()
    $Hasher = [System.Security.Cryptography.SHA256]::Create()
    $HashBytes = $Hasher.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($RawIdentity))
    $FullHash = [System.BitConverter]::ToString($HashBytes).Replace("-", "").ToLower()
    return $FullHash.Substring(0, 32)
}

# Logging function
function Invoke-LogMsg([string]$Text [bool]$Successful = $False) {
    if ([string]::IsNullOrWhiteSpace($Text)) { return }
    $Timestamp = (Get-Date).ToString("HH:mm:ss")
    $ESC = [char]27
    $Reset = "$ESC[0m"
    
    # Base colour for fixer
    $ColorCode = "38;5;36" # Blue

    if $Successful -eq $True {
        $ColorCode = "32" # Green
    }

    $ColorPrefix   = "$ESC[${ColorCode}m[$Timestamp] [Fixer]$Reset"
    $FormattedLine = "$ColorPrefix $Text"
    
    # Write-Host bypasses standard capture to prevent double-logging
    Write-Host $FormattedLine
    
    if (Test-Path -LiteralPath $GlobalLogFile) {
        $RetryCount = 0
        $MaxRetries = 15
        $Success    = $false
        
        while (-not $Success -and $RetryCount -lt $MaxRetries) {
            try {
                [System.IO.File]::AppendAllText($GlobalLogFile, ($FormattedLine + [System.Environment]::NewLine))
                $Success = $true
            } catch [System.IO.IOException] {
                $RetryCount++
                [System.Threading.Thread]::Sleep(50)
            } catch {
                break
            }
        }
    }
}



$ErrorDbPath  = Join-Path $ConfigDir "broken_songs.json"
$BrokenTracks = [System.Collections.Generic.List[PSCustomObject]]::new()

Invoke-LogMsg " Found $BrokenTracks.Length tracks that need fixing"

# Locate all temp playlist run error logs generated by Download.ps1
$ErrorLogs = Get-ChildItem -Path $ConfigDir -Filter "playlist*_run_errors.txt" -File

foreach ($Log in $ErrorLogs) {
    if ($Log.Length -eq 0) { continue }
    
    $RawLines = Get-Content -LiteralPath $Log.FullName -ErrorAction SilentlyContinue
    $CurrentPlaylistIndex = if ($Log.BaseName -match '\d+') { $Matches[0] } else { "Unknown" }

    # Parse errors block-by-block
    for ($i = 0; $i -lt $RawLines.Count; $i++) {
        # Clean out ANSI escape color codes so the regex matches raw text safely
        $Line = $RawLines[$i] -replace '\x1b\[[0-9;]*m', ''

        # Match both the clean text or standard yt-dlp log outputs
        if ($Line -match "ERROR:\s*\[youtube\]\s*([^:]+):\s*(.*)") {
            $VideoID = $Matches[1].Trim()
            $Reason  = $Matches[2].Trim()
            
            # Lookahead logic to catch trailing context warnings
            if ($i + 1 -lt $RawLines.Count) {
                $NextLine = $RawLines[$i+1] -replace '\x1b\[[0-9;]*m', ''
                if ($NextLine -match "Sign in to confirm|Video unavailable|private|not made this video available") {
                    $Reason += " ($($NextLine.Trim()))"
                }
            }

            # Avoid duplication across thread sweeps
            if (-not ($BrokenTracks.videoId -contains $VideoID)) {
                $BrokenTracks.Add([PSCustomObject]@{
                    id         = Get-TrackUUID "Unknown" "Playlist $CurrentPlaylistIndex" $VideoID
                    videoId    = $VideoID
                    title      = "Track ID: $VideoID"
                    playlist   = "Playlist $CurrentPlaylistIndex"
                    reason     = $Reason
                    detectedAt = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
                })
                Write-Output "    [!] Flagged broken track: $VideoID ($Reason)"
            }
        }
    }
}

# Preserve existing un-resolved manual records and update IDs if missing
if (Test-Path $ErrorDbPath) {
    $ExistingDb = Get-Content -LiteralPath $ErrorDbPath -Raw -ErrorAction SilentlyContinue | ConvertFrom-Json
    foreach ($Item in $ExistingDb) {
        if (-not ($BrokenTracks.videoId -contains $Item.videoId)) {
            # Migrate legacy IDs to the new deterministic standard if absent
            if (-not $Item.id -or $Item.id.Length -ne 32) {
                $Item.id = Get-TrackUUID "Unknown" $Item.playlist $Item.videoId
            }
            $BrokenTracks.Add($Item)
        }
    }
}

# Commit to the server database
$BrokenTracks | ConvertTo-Json -Depth 4 | Out-File -FilePath $ErrorDbPath -Encoding utf8 -Force
Write-Output "[FIX ENGINE] Analysis finished. Active anomalies compiled to broken_songs.json."

# Local Standalone Console Trigger Automation (Fallback)
if ($AutoRecover) {
    $GeoTracks = $BrokenTracks | Where-Object { $_.reason -match "available in your country|GeoRestrictedError|not made this video available" }
    if ($GeoTracks.Count -gt 0 -and (Test-Path $ProtonCLI)) {
        Write-Output "[*] Running standalone CLI recovery for $($GeoTracks.Count) country-restricted tracks..."
        & $ProtonCLI c --cc US
        Start-Sleep -Seconds 8
        $Recovered = @()
        foreach ($Track in $GeoTracks) {
            $Url = "https://www.youtube.com/watch?v=$($Track.videoId)"
            & $YTDLPPath --no-colors --embed-metadata --embed-thumbnail --convert-thumbnails jpg -f "ba[ext=m4a]/ba" --cookies $CookiePath -P $BackupDir $Url
            if ($LASTEXITCODE -eq 0) { $Recovered += $Track.videoId }
        }
        & $ProtonCLI d
        if ($Recovered.Count -gt 0) {
            $CurrentDb = Get-Content -LiteralPath $ErrorDbPath -Raw | ConvertFrom-Json
            $CleanedDb = $CurrentDb | Where-Object { $Recovered -notcontains $_.videoId }
            $CleanedDb | ConvertTo-Json -Depth 4 | Out-File -FilePath $ErrorDbPath -Encoding utf8 -Force
        }
    }
}